### ISSUE TITLE
How to Fix Lines See Photo Attachment

### ISSUE THREAD

**Issue by mrzev123** [priyamharsh14/SniffnDetect#10]
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\sniffndetect.py", line 41, in analyze_threader
    self.analyze_packet(pkt)
  File "C:\Users\Administrator\sniffndetect.py", line 80, in analyze_packet
    self.set_flags()
  File "C:\Users\Administrator\sniffndetect.py", line 64, in set_flags
    self.FILTERED_ACTIVITIES[category]['activities'])
  File "C:\Users\Administrator\sniffndetect.py", line 48, in check_avg_time
    time += activities[c][0] - activities[c-1][0]
IndexError: list index out of range

![image](https://user-images.githubusercontent.com/39166589/170692058-b24f8926-98df-492b-bfbd-f3f97e2128bc.png)

**Comment by priyamharsh14** [comment]
@mrzev123 

Sorry for the delay. I haven't been able to maintain this repo lately due to my work.
I will try to go through the code on weekends and fix these issues.

**Comment by mrzev123** [comment]
> @mrzev123
> 
> Sorry for the delay. I haven't been able to maintain this repo lately due to my work. I will try to go through the code on weekends and fix these issues.

Thank you, I'll be waiting
