### ISSUE TITLE
Sniff Detect does not detect attacks that I send to my web server

### ISSUE THREAD

**Issue by SURES20** [priyamharsh14/SniffnDetect#13]
Hello, within our university as part of our study projects, our group has been tasked with conducting a study on the SniffnDetect tool. The goal is to be able to launch DDoS attacks and measure the performance of this tool. To achieve this, we decided to set up a standard network architecture with a malicious machine and a web server.

Web Server contains:
- Apache2
- SniffnDetect

Malicious Machine:
For the attack, we initially tried the SYN Flood attack using various tools such as hping3, MHDDoS, and even with a Python script. However, SniffnDetect does not detect any attacks.

Could you please explain why the attacks are not being detected, or is there documentation explaining how to test this tool?

Thank you.

**Comment by priyamharsh14** [comment]
Hello,

Thank you for your interest in this repository. I would like to inform you that I am not actively maintaining this code at the moment. Please be aware that due to possible changes over time, the code may not function as intended.

However, if you wish to test this script, it is necessary to run it from a web server instance within your network. Additionally, the machine used for testing (attacker machine) should be located in the same local network as the web server to ensure accurate detection of any attacks.

Best regards.

**Comment by SURES20** [comment]
`Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lab702/SniffnDetect/sniffndetect.py", line 41, in analyze_threader
    self.analyze_packet(pkt)
  File "/home/lab702/SniffnDetect/sniffndetect.py", line 80, in analyze_packet
    self.set_flags()
  File "/home/lab702/SniffnDetect/sniffndetect.py", line 63, in set_flags
    self.FILTERED_ACTIVITIES[category]['flag'] = self.check_avg_time(
  File "/home/lab702/SniffnDetect/sniffndetect.py", line 48, in check_avg_time
    time += activities[c][0] - activities[c-1][0]
IndexError: list index out of range`


Hello, thank you for your response. We noticed, while inspecting the code and running it, that the above-mentioned error occurs when sending a SYN Flood attack, for example. The moment the attack is initiated, the program encounters an error, making it impossible for the script to execute properly. Do you know the cause of this error?

Thank you.
