### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Scarner56** [priyamharsh14/SniffnDetect#6]
I just install the modules and run the code it give me a error pls help
```Traceback (most recent call last):
  File "C:\Users\User\Desktop\SniffnDetect-master\app.py", line 8, in <module>
    sniffer = SniffnDetect()
  File "C:\Users\User\Desktop\SniffnDetect-master\sniffndetect.py", line 16, in __init__
    self.MY_IP = [x[4] for x in conf.route.routes if x[2] != '0.0.0.0' and x[3]==self.INTERFACE][0]
IndexError: list index out of range
```

**Comment by priyamharsh14** [comment]
I will check the issue and will let you know.

**Comment by Scarner56** [comment]
Thanks

And what this thing mean?
```
WARNING: No libpcap provider available ! pcap won't be used
```

**Comment by priyamharsh14** [comment]
@Scarner56 

Sorry for the delay. I haven't been able to maintain this repo lately due to my work.
I will try to go through the code on weekends and fix these issues.

**Comment by priyamharsh14** [comment]
> Thanks
> 
> And what this thing mean?
> 
> ```
> WARNING: No libpcap provider available ! pcap won't be used
> ```

this happens when there's some problem with the libpcap library.
Please make sure you have libpcap installed in your system (if it's a Linux machine) or WinPcap / NPcap (if you are using Windows)
